# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f05862c2c315881f43985b2f0568707f5f346c3d65c58076c392e301a2839a49d9a925e3d53ee95f8076d33dd75de5d63d35adf0c44524b1ff4f3f7adccb27e

test:
  secret_key_base: 7642ccb52270ecf8b85931c3d1d3043294ebacbc232728c50df8891a045723eed325d292d4c04270cc943a7bebfe5c12b2924a1da0a9ac1c6d2d424fbfd3c14c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
